"""Add last_vote_date to User model

Revision ID: dd4e5a2ce808
Revises: 
Create Date: 2025-04-19 13:38:20.773128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd4e5a2ce808'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_vote_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.drop_index('unique_user_employee_vote')
        batch_op.create_unique_constraint('unique_user_employee_vote', ['user_id', 'employee_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_employee_vote', type_='unique')
        batch_op.create_index('unique_user_employee_vote', ['user_id', 'employee_id'], unique=1)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_vote_date')

    # ### end Alembic commands ###
